### ISSUE TITLE
Secure view options is offered for every kind of file.

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#283] opened 2019-09-30 13:04 UTC
Tested with ownCloud 10.3.0 alpha2 and  richdocuments: 2.2.0RC

Secure view options should only be offered as an option for the **mime types / file types which are associated with Collabora**. Right now it is offered for every single type of file. e.g. mp4 file shown in the screenshot below.

![Screen Shot 2019-09-30 at 14 49 16](https://user-images.githubusercontent.com/10596560/65881271-77232380-e393-11e9-89eb-af623df4ce38.png)

(cc @pmaier @piotr JFYI)

**Comment by pmaier1** [comment] 2019-10-01 08:28
AFAIK, the options should be shown for
- Folders
- ODF (.odt / .ods / .odp)
- MS Office (.docx / .xlsx / .pptx)
- PDF

@mrow4a please correct me if I missed something

**Comment by mrow4a** [comment] 2019-10-01 08:43
@pmaier1 @davitol yes, and as far as I understood: 
- for shared folders, all other formats then ODF/DOC/PDF will show exception, ODF/DOC/PDF will be opened with watermark in a safe editor
- for shared ODF/DOC/PDF, these will be opened with watermark in a safe editor

**Comment by mrow4a** [comment] 2019-10-01 13:03
@pmaier1 can you confirm that this is not a bug, but requested bahaviour, so that we can close it?

**Comment by pmaier1** [comment] 2019-10-02 13:51
> @pmaier1 can you confirm that this is not a bug, but requested bahaviour, so that we can close it?

Well, in the screenshot there is a MP4 file which can be shared with Secure View restrictions. IMO, this is not the expected behavior as only the resources in https://github.com/owncloud/richdocuments/issues/283#issuecomment-536928339 should be allowed for sharing with Secure View.

**Comment by mrow4a** [comment] 2019-10-02 15:13
@pmaier1 ahh..

Thanks for the review @davitol this is indeed a regression.

**Comment by mrow4a** [comment] 2019-10-08 10:22
fix in https://github.com/owncloud/richdocuments/pull/293

**Closed** 2019-10-10 15:59 UTC
Labels: bug, regression
