### ISSUE TITLE
Cannot connect to document

### ISSUE THREAD

**Issue by Twilek-de** [owncloud/richdocuments#128] opened 2016-10-16 00:33 UTC
Since updating to the latest docker image of collabora with nextcloud I always get a "Well, this is embarrassing, we cannot connect to your document. Please try again." althought the interface loads (see sreenshot). ![2016-10-16 02_29_35-map3womo xls - office - nextcloud - iron](https://cloud.githubusercontent.com/assets/8283684/19414307/b3a73eca-9348-11e6-9470-8adbb4e04284.png)

Are there any known incompatibilities, as the setup used to work with the same settings before...

**Comment by timar** [comment] 2016-10-16 04:46
Duplicate of issue #127.

**Closed by timar** 2016-10-16 04:46 UTC
