### ISSUE TITLE
Wrong activity "owner" when more than one person edits an office document online

### ISSUE THREAD

**Issue by oparoz** [owncloud/richdocuments#106] opened 2016-09-05 11:45 UTC
### Steps to reproduce
1. Ask someone to open a document using Collabora Office
1. Open the same document using Collabora Office
1. Take editing control
1. Make modifications

### Expected behaviour

I should be shown as the author in the activity stream

### Actual behaviour

The other person is shown as the author

**Comment by timar** [comment] 2016-10-17 13:46
This is fixed by https://gerrit.libreoffice.org/gitweb?p=online.git;a=commit;h=9ebd7a15e2864973911e03a4c40eb83ed924515e
It was not a bug in richdocuments, by the way.

**Closed by timar** 2016-10-17 13:46 UTC
Labels: bug

**Comment by oparoz** [comment] 2016-10-17 13:47
Great, thanks!
