### ISSUE TITLE
Collabora/CODE and Richdocuments plugin error with OwnCloud 9.1

### ISSUE THREAD

**Issue by tetuya0703** [owncloud/richdocuments#112] opened 2016-09-18 13:57 UTC
Hi All

I'm construct owncloud9.1.0 in AWS using image in bitnami.
So to use Collabora Online, by making reference to the following web page, richdocument, install.

http://askubuntu.com/questions/775766/how-to-install-the-richdocuments-plugin-on-owncloud

A plug-in of richdocument, install, I made docker in t Collabora Online Development Edition (CODE) start in following CLI.

$ docker pull collabora/code
$ docker run -t -d -p 127.0.0.1:9980:9980 -e \
    "domain=<your-dot-escaped-domain>" --cap-add MKNOD collabora/code
After environment building of Collabora Online Development Edition (CODE)
offie-> test. doc.
this document is clicked, the following error is recorded in owncloud.log.

Error   PHP Argument 4 passed to OCA\Richdocuments\Controller\DocumentController::__construct() must implement interface OCP\IConfig, instance of OCA\Richdocuments\AppConfig given, called in /opt/bitnami/apps/owncloud/htdocs/apps/richdocuments/appinfo/application.php on line 55 and defined at /opt/bitnami/apps/owncloud/htdocs/apps/richdocuments/controller/documentcontroller.php#56 2016-09-09T06:52:01+00:00
It isn't possible to edit document in such state, when how doing do, would I be able to settle it?

**Comment by RealRancor** [comment] 2016-10-01 12:02
@tetuya0703 Duplicate of https://github.com/owncloud/richdocuments/issues/107

Why create another issue if you already have posted in https://github.com/owncloud/richdocuments/issues/107#issuecomment-246214464

Creating duplicated issues most likely won't solve such issues faster.

**Comment by timar** [comment] 2016-10-17 14:05
Duplicate of #107

**Closed by timar** 2016-10-17 14:05 UTC
