### ISSUE TITLE
Using Collabora Online via Federation

### ISSUE THREAD

**Issue by pmaier1** [owncloud/richdocuments#381] opened 2021-02-16 11:55 UTC
**User story**
1. Use Collabora Online for viewing and editing documents collaboratively via federated sharing
2. Use Secure View sharing with Collabora via federation

**Further info**
- For 2.: Secure View via federation has to use the Collabora Server of the owner's instance (otherwise security is undermined!)

---

Needs technical assessment and concept. Please consider both separately. Both should work in the end but having only 1. first would be a good start.

@mrow4a

**Comment by mrow4a** [comment] 2021-02-16 12:30
@pmaier1 can we split it into two subproblems?
1. secure view with collabora via federation
- might be possibly due to read-only character of the feature
 
2. collabora online (edit etc) via federation 
- likely not possible, or if is, I sense problems

**Comment by mrow4a** [comment] 2021-02-16 14:06
@pmaier1 thanks for clarifying in the description, would consider and address challenges separately so we have understanding.

**Comment by mrow4a** [comment] 2021-02-22 08:14
# Technical Concept

## Use-case

- The ownCloud instances **sourcefedinstance** and **destfedinstance** are trusted entities with each other and thus federated shares can be created
- User **user1@sourcefedinstance** shares secure-view or document via federated sharing with **user1@destfedinstance**- As result of this action **fedsharetoken** gets created that permits **user1@destfedinstance** to access file of **user1@sourcefedinstance**, and **fedcollaboratoken** that permits access to **sourcefedinstance** collabora instance. 
- As **user1@destfedinstance** is not known to  **sourcefedinstance** as instance user, thus each access to the file is done via **user1@destfedinstance (on behalf of user1@sourcefedinstance)** (remote access).

## Option 1 - On open redirect to remote federated owncloud instance for access to source collabora
User opening document goes through federated collabora authentication flow (**fedsharetoken** and **collaboratoken**), and gets redirected directly to **sourcefedinstance** instance on specific path to access the collabora. 

- users accesses file from **sourcefedinstance** directly as result of redirect from **destfedinstance**
- as users gets fully redirected, user is under audit and governance of **sourcefedinstance**

### Technical flow:
-  **user1@destfedinstance** accessed federated share file by click "Open in Collabora"
- Request is sent to **destfedinstance** richdocuments app
- richdocuments app requests access token **fedcollaboratoken** from **sourcefedinstance** via **fedsharetoken** that gives access to file. File can only be accessed having valid pair of **fedcollaboratoken** and **fedsharetoken** .
- user gets redirected to **sourcefedinstance** collabora app, as **user1@destfedinstance (on behalf of user1@sourcefedinstance)**, and there accesses the file using standard collabora access.
- if secure view is in place, permissions need to be correctly handled and download should not be possible. Federated share should be accessible vie redirection flow 
- if editing is in place, proper locking mechanism should be in place to avoid synchronisation and file integrity problems.
- proper versioning and APIs need to be defined, in order to avoid incompatibility issues with future software evolvement.

## Option 2 - On open proxy to remove federated owncloud instance via iFrame

User opening document goes through federated collabora authentication flow, and in  **destfedinstance** iFrame is created, that proxies calls to **sourcefedinstance** richdocuments app and thus *sourcefedinstance** collabora instance.

- users accesses file from **sourcefedinstance** as it was in **destfedinstance**, no redirect to **sourcefedinstance** directly
- we would need workarounds to make it work

**Comment by mmeeks** [comment] 2021-02-22 16:14
Thanks for the analysis; of course - it is really important that all users collaboratively editing the same document end up connecting to the same COOL instance / physical address space - otherwise everything goes wrong very quickly. If at all possible I'd prefer the authoritative source of that document also to serve the COOL instance, to make data transfer quick between the storage and COOL itself (important for autosave, and the document never leaving the site it is located at). Not sure how that maps onto the above options - but hopefully it does =)

**Comment by mrow4a** [comment] 2021-02-22 16:19
@mmeeks main difference between Option 1 and 2 is whether user gets redirected to federated instance (complete redirect), or iFrame is presented and redirections are happening as part of that iFrame.

**Comment by mrow4a** [comment] 2021-02-24 07:28
@eszkadev I had a look at https://github.com/owncloud/richdocuments/compare/master...eszkadev:federation . Generally great work and in very good direction. I noticed few things:

- opening file directly works, but not a file in fed shared folder 
- reason for above -> `remote()` calls internally `getWopiInfoForPublicLink ` https://github.com/owncloud/richdocuments/compare/master...eszkadev:federation#diff-f6848853e94bfe83f31f5a03e8e8c1d086eb07a4ba5c6646b2c5001e05a18da2R1370 .  We need to write `getWopiInfoForFedShare` that is a hybrid between `getWopiInfoForPublicLink ` and `getWopiInfoForAuthUser ` . Public links in anonymous user, and we need to make it work as "user1 on behalf of user0", also handle permissions properly as it was  `getWopiInfoForAuthUser ` . Needs careful considerations, probably some development in owncloud/core required
- I tried to dig why Secure View does not work, need some more effort to see what is missing (could be that some development in owncloud/core).
- error handling is largely missing
- to be confirmed, but trusted servers are handled by federation app itself with some settings (would need to look it up)

**Comment by T0mWz** [comment] 2023-04-25 07:32
Is this still on the roadmap, @tbsbdr @mrow4a ?  Would be very appreciated by us. 😅

**Comment by hodyroff** [comment] 2023-05-02 07:55
Yes, we will try for 10.13 ... do you worry about secure view as well or collaboration generally first?

**Comment by jmdeboer-surfsara** [comment] 2023-05-02 11:33
Hi,

Tom is on holiday, so I'll take the liberty to reply: For us the option to collaborate on documents shared via federation has more priority.

If I understand correctly, option 1 would mean that the wopi url in the richdocuments app will become dynamic rather than fixed as it is now, so that the receiver can access the source wopi server. The receiver 'simply' uses the remote wopi server which fetches/saves the document on behalf of the share sender, based on the tokens. And as Michael pointed out, the document never leaves the site.

This would need some validation as the destfedinstance may have the richdocuments app active, while sourcefedinstance does not have a collabora setup. In such a case, the richdocuments app on destfedinstance should not attempt to open the file or even shown that as an option since there is no remote wopi server.

But on the whole it might be a very elegant solution. Care should also be taken that in a load-balanced setup, all users end up on the same backend, so the X-HAProxy-loolwsd header should match.

**Comment by mrow4a** [comment] 2023-06-06 08:20
@T0mWz @jmdeboer-surfsara

To summarize:
- I was under impression, that OC would open incoming federated share in the collabora online server, and that it would open it from external share mount, like it does for any other group/user share. Apparently it does not work up to my tests, but maybe on your instances it works ? For me error `Backends provided no user object for <user>@<server>`. Or I test something wrong and you made it work on your side? 
- This feature here, is to access file from federated share on the server the file resides. So to do it properly. I confirm, that for this to work, both servers need to have richdocuments app active and on version that is compatible.

**Comment by mrow4a** [comment] 2023-06-13 06:42
work started in https://github.com/owncloud/richdocuments/issues/381 . it cherry-picks work from https://github.com/owncloud/richdocuments/pull/382 that had basic handling with assigning "remote user" as editor, adjusted to completely refactored code and added "federated handshake" to allow exchange of "access_token" so that instances can cross-communicate with each other.

**Comment by mrow4a** [comment] 2023-07-13 12:08
work finalised in https://github.com/owncloud/richdocuments/pull/498 :
- includes most important handling for federated share with exchange of information e.g. on who is editing
- now we should do some validation testing with potential customers, I think @T0mWz agreed to try

future work @hodyroff @mmeeks  :
- Resolving display name for the user from DAV Contacts for federated trusted services
- Implement logic for allowing only trusted server (configurable option)

**Comment by mrow4a** [comment] 2023-10-20 13:20
released

**Closed by mrow4a** 2023-10-20 13:20 UTC
