### ISSUE TITLE
Menu entry mentions Secure View when Secure View is not active

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#439] opened 2022-01-11 17:19 UTC
## Seen in owncloud 10.9.1 RC2 with richdocuments 2.7.0 RC2

* admin shares Documents/Example.odt with user01, granting full edit permissions, which removes the secureview checkbox
![image](https://user-images.githubusercontent.com/1108546/148989846-9881ae5b-6d37-4a09-ba41-0e8625cdfaf6.png)
----
* user01  has "Open in Collabora with Secure View" in his 3-dots-menu.
![image](https://user-images.githubusercontent.com/1108546/148990230-7a6e4fcc-9d50-4c4a-b66e-c66def8720cb.png)
* Editing works fine. 

Expected behaviour:
The menu entry should say "Open in Collabora" when the Secure View feature is not active.

**Comment by mrow4a** [comment] 2022-01-19 18:56
Works as designed due to checked option "Open documents in Secure View with watermark by default". ref. https://github.com/owncloud/richdocuments/pull/400 . @jnweiger can you confirm?

**Comment by mrow4a** [comment] 2022-01-19 19:01
![Uploading Screenshot 2022-01-19 at 20.01.15.png…]()

**Comment by mrow4a** [comment] 2022-01-25 17:09
@jnweiger ok, I see your confusion. It actually does not open in Secure View but just adds watermark on the document. Probably option text should be adjusted.

**Comment by mrow4a** [comment] 2022-01-25 17:19
@pmaier1 I kind of agree here https://github.com/owncloud/richdocuments/pull/400 added option to enable sessions with watermarks enforced and still allowing edit/export etc. It can be confusing because Secure View might imply that file will be in "view only" mode instead of just watermarked.

**Comment by pmaier1** [comment] 2022-01-27 12:45
Why do we need the context menu entry "Open in Collabora with Secure View" at all?

**Comment by mrow4a** [comment] 2022-01-27 13:00
@pmaier1 owncloud/enterprise#4578 , owncloud/enterprise#4566

**Comment by mrow4a** [comment] 2022-02-07 16:14
@pmaier1 @jnweiger any resolution here?

**Comment by NannaBarz** [comment] 2022-02-21 09:06
@pmaier1 @jnweiger any news?

**Comment by IljaN** [comment] 2022-02-28 09:24
Should we do anything? :)

**Comment by pmaier1** [comment] 2022-02-28 13:21
Nothing to do at this point.

**Closed** 2022-02-28 13:47 UTC
