### ISSUE TITLE
Documents cannot be created

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/richdocuments#417] opened 2021-07-30 12:26 UTC
No documents can be created in version 2.6.0. When you click on new Document, new Spreadsheet or new Presentation, the error "Invalid Filename" is always displayed.

ownCloud-Version: 10.8.0
richdocuments-Version: 2.6.0RC1

![image](https://user-images.githubusercontent.com/54261654/127652127-9ff07ca6-c973-48d5-9b00-27e5425616ee.png)

The creation of documents works with richdocuments version 2.5.0 and ownCloud version 10.8.0.

Editing of documents is not yet affected by this. Existing documents can be opened, edited and saved.

Logfile:

{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.710900","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: version at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#3"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711200","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: sessionId at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#4"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711200","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: permissions at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#5"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711300","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: title at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#6"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711400","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: fileId at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#7"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711400","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: access_token at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#8"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711500","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: access_token_ttl at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#9"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711500","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: urlsrc at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#10"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711600","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: path at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#11"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711700","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: uploadMaxHumanFilesize at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#50"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711800","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: uploadMaxFilesize at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#58"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711900","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: uploadMaxFilesize at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#60"}
{"reqId":"YQPw5M-@dPxJdgyzi-74xAAAAAc","level":3,"time":"2021-07-30 12:30:28.711900","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/richdocuments\/index","message":"Undefined index: uploadMaxHumanFilesize at \/usr\/local\/src\/owncloud\/custom\/richdocuments\/templates\/documents.php#66"}

**Comment by jnweiger** [comment] 2021-07-30 13:11
@timar FYI

**Comment by JanAckermann** [comment] 2021-07-30 13:47
We need this PR in a RC2 to find out what is happening https://github.com/owncloud/richdocuments/pull/418
Not able to reproduce on my local machine

**Comment by GeraldLeikam** [comment] 2021-07-30 13:50
I can give you access to my machine if you want.

**Comment by JanAckermann** [comment] 2021-07-30 13:51
Would be nice, is this a local machine?

**Comment by GeraldLeikam** [comment] 2021-07-30 13:53
The machine is at hetzner. I'll send you the data in our chat.

**Comment by JanAckermann** [comment] 2021-07-30 14:02
Easy to reproduce, need to implement an edge case! Nice finding!

**Comment by JanAckermann** [comment] 2021-07-30 14:11
Fixed via : https://github.com/owncloud/richdocuments/pull/418

**Closed** 2021-07-30 14:52 UTC
Labels: p2-high
